name: Release Pipeline

permissions:
  packages: write
  deployments: write
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-test:
    uses: ./.github/workflows/build.yml

  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    needs: build-test
    outputs:
      version: ${{ steps.semantic-release.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup pnpm
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 #v4.0.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Semantic Release
        id: semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.SEM_REL_TOKEN }}
        run: |
          pnpm dlx semantic-release --ci
          VERSION=$(cat VERSION || echo "")
          echo "Resolved version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  docker:
    concurrency:
      group: docker-${{ github.ref }}
      cancel-in-progress: true
    needs: release
    name: Build and Push Image ${{ needs.release.outputs.version }}
    if: ${{ needs.release.outputs.version != '' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern=${{ github.ref_name }}
            type=raw,value=${{ needs.release.outputs.version }}
            type=raw,value=latest
            ${{ github.ref_name == 'main' && 'type=raw,value=prod' || '' }}
            ${{ github.ref_name == 'develop' && 'type=raw,value=devel' || '' }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
